sudo: required
services:
  - docker
before_install:
  - docker-compose pull
  - docker-compose up -d
  - ./scripts/install-dependencies.sh
  - cp sites/settings.travis.php sites/default/settings.travis.php
install:
  - ./scripts/site-install.sh
after_install:
  - ./scripts/ssh.sh
script:
  - php core/scripts/run-tests.sh
